### PR TITLE
Senior georgijs

### PR DESCRIPTION
**Pull request by gerapetrov12**
eDITED PULL REQUEST

### CODE REVIEW

**Comment by TiPSYDiPSY** [comment]
vsjo hujna davai po novoj

**Review by TiPSYDiPSY — CHANGES_REQUESTED** [review]
hujna

**Comment by gerapetrov12** [comment]
BJUROKRATI HRENOVI

**Comment by gerapetrov12** [comment]
PROLETARIAT VSEH STRAN

**Comment by gerapetrov12** [comment]
OBEDINJASJA

**Review by TiPSYDiPSY — APPROVED** [review]

**Pull request merged**
